services:
  - name: poster-backend
    type: web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string
      - key: JWT_SECRET
        value: your_jwt_secret
    healthCheckPath: "/api/health"
